// This file is created by egg-ts-helper@1.30.3
// Do not modify this file!!!!!!!!!

import 'egg';
import ExportBase = require('../../../app/controller/base');
import ExportCommon = require('../../../app/controller/common');
import ExportTest = require('../../../app/controller/test');
import ExportAdminAccess = require('../../../app/controller/admin/access');
import ExportAdminBase = require('../../../app/controller/admin/base');
import ExportAdminBbs = require('../../../app/controller/admin/bbs');
import ExportAdminBook = require('../../../app/controller/admin/book');
import ExportAdminBookDetail = require('../../../app/controller/admin/book_detail');
import ExportAdminCash = require('../../../app/controller/admin/cash');
import ExportAdminCashconfirm = require('../../../app/controller/admin/cashconfirm');
import ExportAdminColumn = require('../../../app/controller/admin/column');
import ExportAdminColumnCourse = require('../../../app/controller/admin/column_course');
import ExportAdminCommon = require('../../../app/controller/admin/common');
import ExportAdminCoupon = require('../../../app/controller/admin/coupon');
import ExportAdminCourse = require('../../../app/controller/admin/course');
import ExportAdminFlashsale = require('../../../app/controller/admin/flashsale');
import ExportAdminGroup = require('../../../app/controller/admin/group');
import ExportAdminLive = require('../../../app/controller/admin/live');
import ExportAdminOrder = require('../../../app/controller/admin/order');
import ExportAdminOrderItem = require('../../../app/controller/admin/order_item');
import ExportAdminPost = require('../../../app/controller/admin/post');
import ExportAdminPostComment = require('../../../app/controller/admin/post_comment');
import ExportAdminQuestion = require('../../../app/controller/admin/question');
import ExportAdminRenovation = require('../../../app/controller/admin/renovation');
import ExportAdminRole = require('../../../app/controller/admin/role');
import ExportAdminSchool = require('../../../app/controller/admin/school');
import ExportAdminSchoolUser = require('../../../app/controller/admin/school_user');
import ExportAdminSchoolstaff = require('../../../app/controller/admin/schoolstaff');
import ExportAdminTestpaper = require('../../../app/controller/admin/testpaper');
import ExportAdminUser = require('../../../app/controller/admin/user');
import ExportAdminUserHistory = require('../../../app/controller/admin/user_history');
import ExportAdminUserTest = require('../../../app/controller/admin/user_test');
import ExportMobileBbs = require('../../../app/controller/mobile/bbs');
import ExportMobileBook = require('../../../app/controller/mobile/book');
import ExportMobileColumn = require('../../../app/controller/mobile/column');
import ExportMobileCommon = require('../../../app/controller/mobile/common');
import ExportMobileCoupon = require('../../../app/controller/mobile/coupon');
import ExportMobileCourse = require('../../../app/controller/mobile/course');
import ExportMobileFlashsale = require('../../../app/controller/mobile/flashsale');
import ExportMobileGoods = require('../../../app/controller/mobile/goods');
import ExportMobileGroup = require('../../../app/controller/mobile/group');
import ExportMobileGroupWork = require('../../../app/controller/mobile/group_work');
import ExportMobileHome = require('../../../app/controller/mobile/home');
import ExportMobileLive = require('../../../app/controller/mobile/live');
import ExportMobileLiveComment = require('../../../app/controller/mobile/live_comment');
import ExportMobileNotice = require('../../../app/controller/mobile/notice');
import ExportMobileOrder = require('../../../app/controller/mobile/order');
import ExportMobilePost = require('../../../app/controller/mobile/post');
import ExportMobilePostComment = require('../../../app/controller/mobile/post_comment');
import ExportMobilePostSupport = require('../../../app/controller/mobile/post_support');
import ExportMobileTestpaper = require('../../../app/controller/mobile/testpaper');
import ExportMobileUser = require('../../../app/controller/mobile/user');
import ExportMobileUserCoupon = require('../../../app/controller/mobile/user_coupon');
import ExportMobileUserFava = require('../../../app/controller/mobile/user_fava');
import ExportMobileUserHistory = require('../../../app/controller/mobile/user_history');
import ExportMobileUserTest = require('../../../app/controller/mobile/user_test');
import ExportPcBbs = require('../../../app/controller/pc/bbs');
import ExportPcBook = require('../../../app/controller/pc/book');
import ExportPcColumn = require('../../../app/controller/pc/column');
import ExportPcCommon = require('../../../app/controller/pc/common');
import ExportPcCoupon = require('../../../app/controller/pc/coupon');
import ExportPcCourse = require('../../../app/controller/pc/course');
import ExportPcFlashsale = require('../../../app/controller/pc/flashsale');
import ExportPcGoods = require('../../../app/controller/pc/goods');
import ExportPcGroup = require('../../../app/controller/pc/group');
import ExportPcGroupWork = require('../../../app/controller/pc/group_work');
import ExportPcHome = require('../../../app/controller/pc/home');
import ExportPcLive = require('../../../app/controller/pc/live');
import ExportPcLiveComment = require('../../../app/controller/pc/live_comment');
import ExportPcNotice = require('../../../app/controller/pc/notice');
import ExportPcOrder = require('../../../app/controller/pc/order');
import ExportPcPost = require('../../../app/controller/pc/post');
import ExportPcPostComment = require('../../../app/controller/pc/post_comment');
import ExportPcPostSupport = require('../../../app/controller/pc/post_support');
import ExportPcTestpaper = require('../../../app/controller/pc/testpaper');
import ExportPcUser = require('../../../app/controller/pc/user');
import ExportPcUserCoupon = require('../../../app/controller/pc/user_coupon');
import ExportPcUserFava = require('../../../app/controller/pc/user_fava');
import ExportPcUserHistory = require('../../../app/controller/pc/user_history');
import ExportPcUserTest = require('../../../app/controller/pc/user_test');
import ExportPlatformAccess = require('../../../app/controller/platform/access');
import ExportPlatformRole = require('../../../app/controller/platform/role');

declare module 'egg' {
  interface IController {
    base: ExportBase;
    common: ExportCommon;
    test: ExportTest;
    admin: {
      access: ExportAdminAccess;
      base: ExportAdminBase;
      bbs: ExportAdminBbs;
      book: ExportAdminBook;
      bookDetail: ExportAdminBookDetail;
      cash: ExportAdminCash;
      cashconfirm: ExportAdminCashconfirm;
      column: ExportAdminColumn;
      columnCourse: ExportAdminColumnCourse;
      common: ExportAdminCommon;
      coupon: ExportAdminCoupon;
      course: ExportAdminCourse;
      flashsale: ExportAdminFlashsale;
      group: ExportAdminGroup;
      live: ExportAdminLive;
      order: ExportAdminOrder;
      orderItem: ExportAdminOrderItem;
      post: ExportAdminPost;
      postComment: ExportAdminPostComment;
      question: ExportAdminQuestion;
      renovation: ExportAdminRenovation;
      role: ExportAdminRole;
      school: ExportAdminSchool;
      schoolUser: ExportAdminSchoolUser;
      schoolstaff: ExportAdminSchoolstaff;
      testpaper: ExportAdminTestpaper;
      user: ExportAdminUser;
      userHistory: ExportAdminUserHistory;
      userTest: ExportAdminUserTest;
    }
    mobile: {
      bbs: ExportMobileBbs;
      book: ExportMobileBook;
      column: ExportMobileColumn;
      common: ExportMobileCommon;
      coupon: ExportMobileCoupon;
      course: ExportMobileCourse;
      flashsale: ExportMobileFlashsale;
      goods: ExportMobileGoods;
      group: ExportMobileGroup;
      groupWork: ExportMobileGroupWork;
      home: ExportMobileHome;
      live: ExportMobileLive;
      liveComment: ExportMobileLiveComment;
      notice: ExportMobileNotice;
      order: ExportMobileOrder;
      post: ExportMobilePost;
      postComment: ExportMobilePostComment;
      postSupport: ExportMobilePostSupport;
      testpaper: ExportMobileTestpaper;
      user: ExportMobileUser;
      userCoupon: ExportMobileUserCoupon;
      userFava: ExportMobileUserFava;
      userHistory: ExportMobileUserHistory;
      userTest: ExportMobileUserTest;
    }
    pc: {
      bbs: ExportPcBbs;
      book: ExportPcBook;
      column: ExportPcColumn;
      common: ExportPcCommon;
      coupon: ExportPcCoupon;
      course: ExportPcCourse;
      flashsale: ExportPcFlashsale;
      goods: ExportPcGoods;
      group: ExportPcGroup;
      groupWork: ExportPcGroupWork;
      home: ExportPcHome;
      live: ExportPcLive;
      liveComment: ExportPcLiveComment;
      notice: ExportPcNotice;
      order: ExportPcOrder;
      post: ExportPcPost;
      postComment: ExportPcPostComment;
      postSupport: ExportPcPostSupport;
      testpaper: ExportPcTestpaper;
      user: ExportPcUser;
      userCoupon: ExportPcUserCoupon;
      userFava: ExportPcUserFava;
      userHistory: ExportPcUserHistory;
      userTest: ExportPcUserTest;
    }
    platform: {
      access: ExportPlatformAccess;
      role: ExportPlatformRole;
    }
  }
}
